### ISSUE TITLE
ecb-activate causes failure from void-variable

### ISSUE THREAD

**Issue by dakrone** [ecb-home/ecb#20]
When I try to activate ecb via `ecb-activate`, I get the following error:

```
ecb-clean-up-after-activation-failure: ECB 2.40: Errors during the layout setup of ECB. (error-type: void-variable, error-data: (ecb-examples-bufferinfo-buffer-name))
```

I'm using the latest ECB from Melpa (which is unfortunately still Alex Ott's fork rather than this version)

**Comment by ware** [comment]
Sorry I never got back to you on this @dakrone.  This is fixed in the latest code here.  We'll hopefully get this upstream in Melpa soon.

**Comment by dakrone** [comment]
Great, looking forward to the new build. Thanks @ware!

**Comment by jamespo** [comment]
I get this error with emacs 26.3 & using the Melpa version or cloning this repo directly doesn't fix it
